package br.com.walison.lucros.visao.edicao;

import br.com.walison.lucros.visao.listagem.JListarProdutos;
import br.com.walison.lucros.classes.Janela;
import br.com.walison.lucros.classes.Conexao;
import br.com.walison.lucros.classes.modelos.Fornecedor;
import br.com.walison.lucros.classes.Mensagem;
import br.com.walison.lucros.classes.modelos.Produto;
import br.com.walison.lucros.classes.TrataNumeros;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Walison Cecílio
 */
public class JEditarProduto extends javax.swing.JPanel {

    /**
     * Creates new form JProdutoEditar
     */
    public JEditarProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lNomCadProd = new javax.swing.JLabel();
        cNomCadProd = new javax.swing.JTextField();
        lMarCadProd = new javax.swing.JLabel();
        cMarCadProd = new javax.swing.JTextField();
        lVlVenCadProd = new javax.swing.JLabel();
        cVlVenCadProd = new javax.swing.JFormattedTextField();
        radioUnidade = new javax.swing.JRadioButton();
        radioPeso = new javax.swing.JRadioButton();
        bCadCadProd = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cDesCadProd = new javax.swing.JTextPane();
        lDecCadProd1 = new javax.swing.JLabel();
        cCodBar = new javax.swing.JTextField();

        jLabel13.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        jLabel13.setText("EDITAR PRODUTO");

        lNomCadProd.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lNomCadProd.setText("NOME:  *");

        cNomCadProd.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        lMarCadProd.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lMarCadProd.setText("MARCA:  *");

        cMarCadProd.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        lVlVenCadProd.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lVlVenCadProd.setText("VALOR DE VENDA:  *");

        try {
            cVlVenCadProd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("R$ ##.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cVlVenCadProd.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        cVlVenCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cVlVenCadProdActionPerformed(evt);
            }
        });

        radioUnidade.setText("UNIDADE");
        radioUnidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioUnidadeMouseClicked(evt);
            }
        });

        radioPeso.setText("PESO");
        radioPeso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioPesoMouseClicked(evt);
            }
        });
        radioPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPesoActionPerformed(evt);
            }
        });

        bCadCadProd.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        bCadCadProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/salvar.png"))); // NOI18N
        bCadCadProd.setToolTipText("Cadastrar Produto");
        bCadCadProd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bCadCadProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCadCadProdMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Cantarell", 1, 12)); // NOI18N
        jLabel9.setText("CAMPOS CONTENDO * SÃO OBRIGATÓTIOS");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/voltar.png"))); // NOI18N
        jButton1.setToolTipText("Voltar");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel1.setText("COD DE BARRA:");

        cDesCadProd.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(cDesCadProd);

        lDecCadProd1.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lDecCadProd1.setText("DESCRIÇÃO DO PRODUTO:");

        cCodBar.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lDecCadProd1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(355, 355, 355)
                                .addComponent(jLabel13))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cCodBar, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lNomCadProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cNomCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lMarCadProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cMarCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lVlVenCadProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cVlVenCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(radioUnidade)
                                .addGap(31, 31, 31)
                                .addComponent(radioPeso))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel9)
                        .addGap(200, 200, 200)
                        .addComponent(bCadCadProd)
                        .addGap(120, 120, 120)
                        .addComponent(jButton1)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lMarCadProd)
                            .addComponent(jLabel1)
                            .addComponent(lNomCadProd)
                            .addComponent(cNomCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cMarCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cCodBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(109, 109, 109)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lVlVenCadProd)
                            .addComponent(cVlVenCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioUnidade)
                            .addComponent(radioPeso))
                        .addGap(116, 116, 116)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lDecCadProd1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(bCadCadProd))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(80, 80, 80))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1283, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 737, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cVlVenCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cVlVenCadProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cVlVenCadProdActionPerformed

    private void radioUnidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioUnidadeMouseClicked
        this.getRadioPeso().setSelected(false);
        this.setUnidade(true);
    }//GEN-LAST:event_radioUnidadeMouseClicked

    private void radioPesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioPesoMouseClicked
        this.getRadioUnidade().setSelected(false);
        this.setUnidade(false);
    }//GEN-LAST:event_radioPesoMouseClicked

    private void radioPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioPesoActionPerformed

    private void bCadCadProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCadCadProdMouseClicked
        try {
            this.EditarProduto();
        } catch (SQLException ex) {
            Logger.getLogger(JEditarProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bCadCadProdMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            this.j.voltar();
        } catch (SQLException ex) {
            Logger.getLogger(JEditarProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCadCadProd;
    private javax.swing.JTextField cCodBar;
    private javax.swing.JTextPane cDesCadProd;
    private javax.swing.JTextField cMarCadProd;
    private javax.swing.JTextField cNomCadProd;
    private javax.swing.JFormattedTextField cVlVenCadProd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lDecCadProd1;
    private javax.swing.JLabel lMarCadProd;
    private javax.swing.JLabel lNomCadProd;
    private javax.swing.JLabel lVlVenCadProd;
    private javax.swing.JRadioButton radioPeso;
    private javax.swing.JRadioButton radioUnidade;
    // End of variables declaration//GEN-END:variables
    private Janela j;
    private Janela j2;
    private Produto p;
    private LinkedList<Fornecedor> fornecedores;
    private NumberFormat dim = NumberFormat.getCurrencyInstance();
    private boolean unidade;
    private Mensagem mensagem = new Mensagem();
    
    public void voltar() throws SQLException{
        this.j2 = new Janela();
        JListarProdutos a = new JListarProdutos();
        a.setProdutos(a.getSis().BuscarProdutos());
            
        DefaultTableModel modeloTable = (DefaultTableModel) a.getTabela().getModel();

        for(Produto p : a.getProdutos()){
            Object linha[] = { p.getCod_prod(), p, p.getMar_prod(), this.dim.format(p.getVl_prod()), p.getQtd_estoque()  };
            modeloTable.addRow(linha);   
        }
        a.setJ(this.j2);
        this.j2.setPanel(a);
        this.j2.add(this.j2.getPanel());
        
        this.j.dispose();
    }
    
    public void EditarProduto() throws SQLException{
        Connection conexao = new Conexao().getConexao();
        TrataNumeros trataNumeros = new TrataNumeros();

        String sql = "UPDATE produtos SET nom_prod = ?, mar_prod = ?, vl_prod = ?, cod_bar_prod = ?, desc_prod = ?, unidade = ? WHERE cod_prod = ?;";
        
        try {
            PreparedStatement stmt = conexao.prepareStatement(sql);
            
            stmt.setString(1, this.cNomCadProd.getText().toUpperCase());
            stmt.setString(2, this.cMarCadProd.getText().toUpperCase());
            stmt.setFloat(3, trataNumeros.trataDinheiro(this.cVlVenCadProd.getText()));
            stmt.setString(4, this.getcCodBar().getText());
            stmt.setString(5, this.cDesCadProd.getText().toUpperCase());
            stmt.setBoolean(6, this.unidade);
            stmt.setInt(7, this.p.getCod_prod());
            
            this.mensagem.msg("Alterações Feitas com Sucesso!!");
            stmt.execute();
            conexao.commit();
            this.voltar();
        } catch (SQLException ex) {
            conexao.rollback();
        } finally {
            conexao.close();
        }
    }
    
    
    /**
     * @return the j
     */
    public Janela getJ() {
        return j;
    }

    /**
     * @param j the j to set
     */
    public void setJ(Janela j) {
        this.j = j;
    }

    /**
     * @return the p
     */
    public Produto getP() {
        return p;
    }

    /**
     * @param p the p to set
     */
    public void setP(Produto p) {
        this.p = p;
    }

    /**
     * @return the bCadCadProd
     */
    public javax.swing.JButton getbCadCadProd() {
        return bCadCadProd;
    }

    /**
     * @return the cDesCadProd
     */
    public javax.swing.JTextPane getcDesCadProd() {
        return cDesCadProd;
    }


    /**
     * @return the cMarCadProd
     */
    public javax.swing.JTextField getcMarCadProd() {
        return cMarCadProd;
    }

    /**
     * @return the cNomCadProd
     */
    public javax.swing.JTextField getcNomCadProd() {
        return cNomCadProd;
    }


    /**
     * @return the cVlVenCadProd
     */
    public javax.swing.JFormattedTextField getcVlVenCadProd() {
        return cVlVenCadProd;
    }

    /**
     * @return the fornecedores
     */
    public LinkedList<Fornecedor> getFornecedores() {
        return fornecedores;
    }

    /**
     * @param fornecedores the fornecedores to set
     */
    public void setFornecedores(LinkedList<Fornecedor> fornecedores) {
        this.fornecedores = fornecedores;
    }

    /**
     * @return the unidade
     */
    public boolean isUnidade() {
        return unidade;
    }

    /**
     * @param unidade the unidade to set
     */
    public void setUnidade(boolean unidade) {
        this.unidade = unidade;
    }

    /**
     * @return the radioPeso
     */
    public javax.swing.JRadioButton getRadioPeso() {
        return radioPeso;
    }

    /**
     * @return the radioUnidade
     */
    public javax.swing.JRadioButton getRadioUnidade() {
        return radioUnidade;
    }

    /**
     * @return the cCodBar
     */
    public javax.swing.JTextField getcCodBar() {
        return cCodBar;
    }   
}
