package br.com.walison.lucros.visao.edicao;

import br.com.walison.lucros.visao.listagem.JListarClientes;
import br.com.walison.lucros.classes.Janela;
import br.com.walison.lucros.classes.modelos.Cliente;
import br.com.walison.lucros.classes.Conexao;
import br.com.walison.lucros.classes.FormatoNumerico;
import br.com.walison.lucros.classes.Mensagem;
import br.com.walison.lucros.classes.TrataNumeros;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Walison Cecílio
 */
public class JEditarCliente extends javax.swing.JPanel {

    /**
     * Creates new form JEditarCliente
     */
    public JEditarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cNomCadCli = new javax.swing.JTextField();
        cSobNomCadCli = new javax.swing.JTextField();
        lSobNomCadCli = new javax.swing.JLabel();
        lNomCadCli = new javax.swing.JLabel();
        lDatCadCli = new javax.swing.JLabel();
        lRuaCadCli = new javax.swing.JLabel();
        cRuaCadCli = new javax.swing.JTextField();
        lNumCadCli = new javax.swing.JLabel();
        cNumCadCli = new javax.swing.JFormattedTextField();
        cDatCadCli = new javax.swing.JFormattedTextField();
        lTelCadCli = new javax.swing.JLabel();
        cTelCadCli = new javax.swing.JFormattedTextField();
        cConjCadCli = new javax.swing.JTextField();
        lConjCadCli = new javax.swing.JLabel();
        lBaiCadCli = new javax.swing.JLabel();
        lLimCadCli = new javax.swing.JLabel();
        lDatPagCadCli = new javax.swing.JLabel();
        cCpfCadCli = new javax.swing.JFormattedTextField();
        lCpfCadCli = new javax.swing.JLabel();
        cDatPagCadCli = new javax.swing.JFormattedTextField();
        cCidCadCli = new javax.swing.JTextField();
        lCidCadCli = new javax.swing.JLabel();
        cBaiCadCli = new javax.swing.JTextField();
        bCadCadCli = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cLimCadCli = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();

        jLabel12.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        jLabel12.setText("EDITAR DE CLIENTE");

        cNomCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        cNomCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNomCadCliActionPerformed(evt);
            }
        });
        cNomCadCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cNomCadCliKeyPressed(evt);
            }
        });

        cSobNomCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        cSobNomCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSobNomCadCliActionPerformed(evt);
            }
        });
        cSobNomCadCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cSobNomCadCliKeyPressed(evt);
            }
        });

        lSobNomCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lSobNomCadCli.setText("SOBRENOME:  *");

        lNomCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lNomCadCli.setText("NOME:  *");

        lDatCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lDatCadCli.setText("DATA NASCIMENTO:");

        lRuaCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lRuaCadCli.setText("RUA:");

        cRuaCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        cRuaCadCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cRuaCadCliKeyPressed(evt);
            }
        });

        lNumCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lNumCadCli.setText("NÚMERO:");

        try {
            cNumCadCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cNumCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        cNumCadCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cNumCadCliKeyPressed(evt);
            }
        });

        try {
            cDatCadCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cDatCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        cDatCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cDatCadCliActionPerformed(evt);
            }
        });
        cDatCadCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cDatCadCliKeyPressed(evt);
            }
        });

        lTelCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lTelCadCli.setText("CONTATO:");

        try {
            cTelCadCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cTelCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        cTelCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTelCadCliActionPerformed(evt);
            }
        });
        cTelCadCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cTelCadCliKeyPressed(evt);
            }
        });

        cConjCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        cConjCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cConjCadCliActionPerformed(evt);
            }
        });
        cConjCadCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cConjCadCliKeyPressed(evt);
            }
        });

        lConjCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lConjCadCli.setText("CONJUNTO:");

        lBaiCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lBaiCadCli.setText("BAIRRO:");

        lLimCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lLimCadCli.setText("LIMITE:  *");

        lDatPagCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lDatPagCadCli.setText("DIA DE PAGAMENTO:  *");

        try {
            cCpfCadCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cCpfCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        cCpfCadCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cCpfCadCliKeyPressed(evt);
            }
        });

        lCpfCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lCpfCadCli.setText("CPF:  *");

        try {
            cDatPagCadCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cDatPagCadCli.setToolTipText("Dia");
        cDatPagCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        cDatPagCadCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cDatPagCadCliKeyPressed(evt);
            }
        });

        cCidCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        cCidCadCli.setText("ESTÂNCIA");
        cCidCadCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cCidCadCliKeyPressed(evt);
            }
        });

        lCidCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lCidCadCli.setText("CIDADE:");

        cBaiCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        cBaiCadCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cBaiCadCliKeyPressed(evt);
            }
        });

        bCadCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        bCadCadCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/salvar.png"))); // NOI18N
        bCadCadCli.setToolTipText("Cadastrar Cliente");
        bCadCadCli.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bCadCadCli.setBorderPainted(false);
        bCadCadCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCadCadCliMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 12)); // NOI18N
        jLabel2.setText("CAMPOS CONTENDO * SÃO OBRIGATÓTIOS");

        try {
            cLimCadCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("R$ ###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cLimCadCli.setText("R$ 100");
        cLimCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        cLimCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cLimCadCliActionPerformed(evt);
            }
        });
        cLimCadCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cLimCadCliKeyPressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/voltar.png"))); // NOI18N
        jButton1.setToolTipText("Voltar");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lRuaCadCli)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cRuaCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lNumCadCli)
                                        .addGap(7, 7, 7)
                                        .addComponent(cNumCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lConjCadCli))
                                    .addComponent(lDatCadCli))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(297, 297, 297)
                                        .addComponent(cLimCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(bCadCadCli)
                                                .addGap(100, 100, 100)
                                                .addComponent(jButton1))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(cConjCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lBaiCadCli)
                                                .addGap(18, 18, 18)
                                                .addComponent(cBaiCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(18, 18, 18)
                                .addComponent(lCidCadCli)
                                .addGap(18, 18, 18)
                                .addComponent(cCidCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lNomCadCli)
                                .addGap(1, 1, 1)
                                .addComponent(cNomCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lSobNomCadCli)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cSobNomCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lCpfCadCli)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cCpfCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cDatCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lTelCadCli)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cTelCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(lLimCadCli)
                                .addGap(126, 126, 126)
                                .addComponent(lDatPagCadCli)
                                .addGap(3, 3, 3)
                                .addComponent(cDatPagCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(433, 433, 433)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel12)
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNomCadCli)
                    .addComponent(cNomCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSobNomCadCli)
                    .addComponent(cSobNomCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCpfCadCli)
                    .addComponent(cCpfCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDatCadCli)
                    .addComponent(cDatCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTelCadCli)
                    .addComponent(cTelCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lLimCadCli)
                    .addComponent(cLimCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDatPagCadCli)
                    .addComponent(cDatPagCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lRuaCadCli)
                    .addComponent(cRuaCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNumCadCli)
                    .addComponent(lConjCadCli)
                    .addComponent(cConjCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lBaiCadCli)
                    .addComponent(cBaiCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCidCadCli)
                    .addComponent(cCidCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cNumCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bCadCadCli)
                    .addComponent(jButton1))
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cNomCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNomCadCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cNomCadCliActionPerformed

    private void cNomCadCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cNomCadCliKeyPressed
        this.eventoClique(evt);        
    }//GEN-LAST:event_cNomCadCliKeyPressed

    private void cSobNomCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSobNomCadCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cSobNomCadCliActionPerformed

    private void cSobNomCadCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cSobNomCadCliKeyPressed
        this.eventoClique(evt); 
    }//GEN-LAST:event_cSobNomCadCliKeyPressed

    private void cRuaCadCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cRuaCadCliKeyPressed
        this.eventoClique(evt); 
    }//GEN-LAST:event_cRuaCadCliKeyPressed

    private void cNumCadCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cNumCadCliKeyPressed
        this.eventoClique(evt);
    }//GEN-LAST:event_cNumCadCliKeyPressed

    private void cDatCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cDatCadCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cDatCadCliActionPerformed

    private void cDatCadCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cDatCadCliKeyPressed
        this.eventoClique(evt); 
    }//GEN-LAST:event_cDatCadCliKeyPressed

    private void cTelCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTelCadCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cTelCadCliActionPerformed

    private void cTelCadCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cTelCadCliKeyPressed
        this.eventoClique(evt);
    }//GEN-LAST:event_cTelCadCliKeyPressed

    private void cConjCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cConjCadCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cConjCadCliActionPerformed

    private void cConjCadCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cConjCadCliKeyPressed
        this.eventoClique(evt);
    }//GEN-LAST:event_cConjCadCliKeyPressed

    private void cCpfCadCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cCpfCadCliKeyPressed
        this.eventoClique(evt); 
    }//GEN-LAST:event_cCpfCadCliKeyPressed

    private void cDatPagCadCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cDatPagCadCliKeyPressed
        this.eventoClique(evt); 
    }//GEN-LAST:event_cDatPagCadCliKeyPressed

    private void cCidCadCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cCidCadCliKeyPressed
        this.eventoClique(evt);       
    }//GEN-LAST:event_cCidCadCliKeyPressed

    private void cBaiCadCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cBaiCadCliKeyPressed
        this.eventoClique(evt);
    }//GEN-LAST:event_cBaiCadCliKeyPressed

    private void bCadCadCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCadCadCliMouseClicked
        try {
            this.editar();
        } catch (SQLException ex) {
            Logger.getLogger(JEditarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bCadCadCliMouseClicked

    private void cLimCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cLimCadCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cLimCadCliActionPerformed

    private void cLimCadCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cLimCadCliKeyPressed
        this.eventoClique(evt);
    }//GEN-LAST:event_cLimCadCliKeyPressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            this.getJ().voltar();
        } catch (SQLException ex) {
            Logger.getLogger(JEditarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCadCadCli;
    private javax.swing.JTextField cBaiCadCli;
    private javax.swing.JTextField cCidCadCli;
    private javax.swing.JTextField cConjCadCli;
    private javax.swing.JFormattedTextField cCpfCadCli;
    private javax.swing.JFormattedTextField cDatCadCli;
    private javax.swing.JFormattedTextField cDatPagCadCli;
    private javax.swing.JFormattedTextField cLimCadCli;
    private javax.swing.JTextField cNomCadCli;
    private javax.swing.JFormattedTextField cNumCadCli;
    private javax.swing.JTextField cRuaCadCli;
    private javax.swing.JTextField cSobNomCadCli;
    private javax.swing.JFormattedTextField cTelCadCli;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lBaiCadCli;
    private javax.swing.JLabel lCidCadCli;
    private javax.swing.JLabel lConjCadCli;
    private javax.swing.JLabel lCpfCadCli;
    private javax.swing.JLabel lDatCadCli;
    private javax.swing.JLabel lDatPagCadCli;
    private javax.swing.JLabel lLimCadCli;
    private javax.swing.JLabel lNomCadCli;
    private javax.swing.JLabel lNumCadCli;
    private javax.swing.JLabel lRuaCadCli;
    private javax.swing.JLabel lSobNomCadCli;
    private javax.swing.JLabel lTelCadCli;
    // End of variables declaration//GEN-END:variables
    private Janela j;
    private Janela j2;
    private Cliente cliente;
    
    private void editar () throws SQLException {
        String sqlCliente = "UPDATE clientes SET nom_cli = ?, sob_nom_cli = ?, " +
                "cpf_cli = ?, dt_nasc_cli = ?, rua_cli = ?, num_cas_cli = ?, conj_cli = ?, bai_cli = ?, " +
                "cid_cli = ?, tel_cli = ? WHERE cod_cli = ?;"; 
        
        String sqlConta = "UPDATE contas SET lim_con = ?, dt_pag = ? WHERE cod_con = ?;";
     
        Connection conexao = new Conexao().getConexao();
        
        PreparedStatement stmtCliente = conexao.prepareStatement(sqlCliente);
        PreparedStatement stmtConta = conexao.prepareStatement(sqlConta);
        
        try {  
            this.preparaStatment(stmtCliente, stmtConta);
            stmtConta.execute();
            stmtCliente.execute();

            conexao.commit();
            new Mensagem().msg("Alterações Feitas com Sucesso!!");
            this.voltar();
        } catch (SQLException ex) {
            new Mensagem().msg("Não conceguimos alterar os dados!!");
            conexao.rollback();
        } finally {
            conexao.close();
        }
    }
    
    private void preparaStatment(PreparedStatement stmtCliente, PreparedStatement stmtConta) throws SQLException {
        TrataNumeros trataNumeros = new TrataNumeros();
        
        stmtCliente.setString(1, this.cNomCadCli.getText().toUpperCase());
        stmtCliente.setString(2, this.cSobNomCadCli.getText().toUpperCase());
        stmtCliente.setString(3, trataNumeros.trataNumeros(this.cCpfCadCli.getText()));
        stmtCliente.setString(4, trataNumeros.trataDatas(this.cDatCadCli.getText()));
        stmtCliente.setString(5, this.cRuaCadCli.getText().toUpperCase());
        stmtCliente.setString(6, this.cNumCadCli.getText());
        stmtCliente.setString(7, this.cConjCadCli.getText().toUpperCase());
        stmtCliente.setString(8, this.cBaiCadCli.getText().toUpperCase());
        stmtCliente.setString(9, this.cCidCadCli.getText().toUpperCase());
        stmtCliente.setString(10, this.cTelCadCli.getText());
        stmtCliente.setFloat(11, this.cliente.getCod_cli());
        
        stmtConta.setFloat(1, trataNumeros.trataDinheiro(this.cLimCadCli.getText()));
        stmtConta.setString(2, this.cDatPagCadCli.getText());
        stmtConta.setShort(3, this.cliente.getConta().getCod_con());        
    }
    
    private void voltar () throws SQLException {
        FormatoNumerico f = new FormatoNumerico();
        this.j2 = new Janela();
        JListarClientes a = new JListarClientes();
        
        a.setJ(new Janela()); 
        a.setClientes(a.getSis().BuscarClientes());

        DefaultTableModel modeloTable = (DefaultTableModel) a.getTabela().getModel();

        for(Cliente c : a.getClientes()){
            Object linha[] = { c, c.getCpf_cli(), c.getConta().getCod_con(), f.din(c.getConta().getLim_con()), f.din(c.getConta().getSal_con()), f.din(c.getConta().getDiv_con()) };
            modeloTable.addRow(linha);   
        }
        
        a.setJ(this.j2);
        this.j2.setPanel(a);
        this.j2.add(this.j2.getPanel());
        
        this.j.dispose();
    }

    /**
     * @return the cBaiCadCli
     */
    public javax.swing.JTextField getcBaiCadCli() {
        return cBaiCadCli;
    }

    /**
     * @return the cCidCadCli
     */
    public javax.swing.JTextField getcCidCadCli() {
        return cCidCadCli;
    }

    /**
     * @return the cConjCadCli
     */
    public javax.swing.JTextField getcConjCadCli() {
        return cConjCadCli;
    }

    /**
     * @return the cCpfCadCli
     */
    public javax.swing.JFormattedTextField getcCpfCadCli() {
        return cCpfCadCli;
    }

    /**
     * @return the cDatCadCli
     */
    public javax.swing.JFormattedTextField getcDatCadCli() {
        return cDatCadCli;
    }

    /**
     * @return the cDatPagCadCli
     */
    public javax.swing.JFormattedTextField getcDatPagCadCli() {
        return cDatPagCadCli;
    }

    /**
     * @return the cLimCadCli
     */
    public javax.swing.JFormattedTextField getcLimCadCli() {
        return cLimCadCli;
    }

    /**
     * @return the cNomCadCli
     */
    public javax.swing.JTextField getcNomCadCli() {
        return cNomCadCli;
    }

    /**
     * @return the cNumCadCli
     */
    public javax.swing.JFormattedTextField getcNumCadCli() {
        return cNumCadCli;
    }

    /**
     * @return the cRuaCadCli
     */
    public javax.swing.JTextField getcRuaCadCli() {
        return cRuaCadCli;
    }

    /**
     * @return the cSobNomCadCli
     */
    public javax.swing.JTextField getcSobNomCadCli() {
        return cSobNomCadCli;
    }

    /**
     * @return the cTelCadCli
     */
    public javax.swing.JFormattedTextField getcTelCadCli() {
        return cTelCadCli;
    }

    /**
     * @return the j
     */
    public Janela getJ() {
        return j;
    }

    /**
     * @param j the j to set
     */
    public void setJ(Janela j) {
        this.j = j;
    }

    /**
     * @return the cliente
     */
    public Cliente getCliente() {
        return cliente;
    }

    /**
     * @param cliente the cliente to set
     */
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    private void eventoClique(KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                this.editar();
            } catch (SQLException ex) {
                Logger.getLogger(JEditarCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
    }    
}
