package br.com.walison.lucros.visao.login;



import br.com.walison.lucros.classes.Conexao;
import br.com.walison.lucros.classes.GeraCriptografa;
import br.com.walison.lucros.classes.Sistema;
import br.com.walison.lucros.classes.Tela;
import br.com.walison.lucros.classes.Janela;
import br.com.walison.lucros.visao.JPrincipal;
import java.awt.event.KeyEvent;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Walison Cecílio
 */
public class JLogin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public JLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cUsuario = new javax.swing.JTextField();
        cSenha = new javax.swing.JPasswordField();
        lNomeUsuario = new javax.swing.JLabel();
        lSenhaUsuario = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LUCROS 2017.1.1: LOGIN");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        cUsuario.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        cUsuario.setText("admin");
        cUsuario.setRequestFocusEnabled(false);
        cUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUsuarioActionPerformed(evt);
            }
        });

        cSenha.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        cSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSenhaActionPerformed(evt);
            }
        });
        cSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cSenhaKeyPressed(evt);
            }
        });

        lNomeUsuario.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        lNomeUsuario.setText("NOME DE USUÁRIO");

        lSenhaUsuario.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        lSenhaUsuario.setText("SENHA");

        jButton1.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        jButton1.setText("LOGAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cSenha)
                    .addComponent(cUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(lNomeUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(lSenhaUsuario)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cSenha, cUsuario});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lNomeUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lSenhaUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cSenha, cUsuario});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cUsuarioActionPerformed

    private void cSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cSenhaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            this.logar();
        } catch (SQLException ex) {
            Logger.getLogger(JLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
             try {
                 this.logar();
             } catch (SQLException ex) {
                 Logger.getLogger(JLogin.class.getName()).log(Level.SEVERE, null, ex);
             }
         }
    }//GEN-LAST:event_formKeyPressed

    private void cSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cSenhaKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
           try {
               this.logar();
           } catch (SQLException ex) {
               Logger.getLogger(JLogin.class.getName()).log(Level.SEVERE, null, ex);
           }
         }
    }//GEN-LAST:event_cSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cSenha;
    private javax.swing.JTextField cUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lNomeUsuario;
    private javax.swing.JLabel lSenhaUsuario;
    // End of variables declaration//GEN-END:variables
    private Janela j = new Janela();
    
    private void logar() throws SQLException{
        Connection conexao = new Conexao().getConexao();
        
        byte senha[] = null;
        try {
            senha = new GeraCriptografa().criptografar(this.cSenha.getText());
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(JLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String senh = "";
        
        for(int i = 0; i < senha.length; i++){
            senh += senha[i];
        }
       
        String sql = "SELECT * FROM usuarios WHERE nom_usu = ? AND sen_usu = ?";
        ResultSet result;
        
        try {
            PreparedStatement stmt = conexao.prepareStatement(sql);
            stmt.setString(1, this.cUsuario.getText());
            stmt.setString(2, senh);
            result = stmt.executeQuery();
            
            if(!result.isBeforeFirst()){
                JOptionPane.showMessageDialog(null, "Login errado, tente novamente!");
                this.cSenha.setText("");
                this.cSenha.requestFocus();
            }else{
                conexao.close();
                Tela t = new Tela();

                JPrincipal a = new JPrincipal();
                a.setJ(j);
                a.setProdutos(new Sistema().BuscarProdutosArvore());

                a.getPanelCli().setVisible(false);
                this.j.setPanel(a);
                this.j.add(j.getMenu());
                this.j.add(this.j.getPanel());
                j.getMenu().setJanelaFechar(j);
                this.dispose();
            }            
        } catch (SQLException ex) {
            Logger.getLogger(JLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public JTextField getSenha(){
        return this.cSenha;
    }
}

