    package br.com.walison.lucros.visao.cadastros;

import br.com.walison.lucros.classes.Janela;
import br.com.walison.lucros.classes.Conexao;
import br.com.walison.lucros.classes.GeraCriptografa;
import br.com.walison.lucros.classes.Mensagem;
import br.com.walison.lucros.classes.TrataNumeros;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Walison Cecílio
 */
public class JCadastroProduto extends javax.swing.JPanel {

    /**
     * Creates new form JCadastroProdutos
     */
    public JCadastroProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        lNomCadProd = new javax.swing.JLabel();
        cNomCadProd = new javax.swing.JTextField();
        lMarCadProd = new javax.swing.JLabel();
        cMarCadProd = new javax.swing.JTextField();
        lVlVenCadProd = new javax.swing.JLabel();
        cVlVenCadProd = new javax.swing.JFormattedTextField();
        radioUnidade = new javax.swing.JRadioButton();
        radioPeso = new javax.swing.JRadioButton();
        bCadCadProd = new javax.swing.JButton();
        bLimCadProd = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cDesCadProd = new javax.swing.JTextPane();
        lDecCadProd1 = new javax.swing.JLabel();
        cCodBar = new javax.swing.JTextField();

        jLabel13.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        jLabel13.setText("CADASTRO DE PRODUTO");

        lNomCadProd.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lNomCadProd.setText("NOME:  *");

        cNomCadProd.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        cNomCadProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cNomCadProdKeyReleased(evt);
            }
        });

        lMarCadProd.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lMarCadProd.setText("MARCA:  *");

        cMarCadProd.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        lVlVenCadProd.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lVlVenCadProd.setText("VALOR DE VENDA:  *");

        try {
            cVlVenCadProd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("R$ ##.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cVlVenCadProd.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        cVlVenCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cVlVenCadProdActionPerformed(evt);
            }
        });

        radioUnidade.setText("UNIDADE");
        radioUnidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioUnidadeMouseClicked(evt);
            }
        });

        radioPeso.setText("PESO");
        radioPeso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioPesoMouseClicked(evt);
            }
        });
        radioPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPesoActionPerformed(evt);
            }
        });

        bCadCadProd.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        bCadCadProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/salvar.png"))); // NOI18N
        bCadCadProd.setToolTipText("Cadastrar Produto");
        bCadCadProd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bCadCadProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCadCadProdMouseClicked(evt);
            }
        });

        bLimCadProd.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        bLimCadProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/lixeira.png"))); // NOI18N
        bLimCadProd.setToolTipText("Limpar Campos");
        bLimCadProd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bLimCadProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLimCadProdMouseClicked(evt);
            }
        });
        bLimCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimCadProdActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Cantarell", 1, 12)); // NOI18N
        jLabel9.setText("CAMPOS CONTENDO * SÃO OBRIGATÓTIOS");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/voltar.png"))); // NOI18N
        jButton1.setToolTipText("Voltar");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel1.setText("COD DE BARRA:");

        cDesCadProd.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(cDesCadProd);

        lDecCadProd1.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lDecCadProd1.setText("DESCRIÇÃO DO PRODUTO:");

        cCodBar.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        cCodBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cCodBarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lDecCadProd1)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cCodBar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lVlVenCadProd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cVlVenCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radioUnidade)
                                        .addGap(31, 31, 31)
                                        .addComponent(radioPeso))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lNomCadProd)
                                        .addGap(18, 18, 18)
                                        .addComponent(cNomCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(lMarCadProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cMarCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel9)
                        .addGap(152, 152, 152)
                        .addComponent(bCadCadProd)
                        .addGap(110, 110, 110)
                        .addComponent(bLimCadProd)
                        .addGap(109, 109, 109)
                        .addComponent(jButton1)))
                .addContainerGap(191, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(416, 416, 416))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel13)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNomCadProd)
                    .addComponent(cNomCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lMarCadProd)
                    .addComponent(cMarCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cCodBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lVlVenCadProd)
                            .addComponent(cVlVenCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioUnidade)
                            .addComponent(radioPeso))
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lDecCadProd1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(bCadCadProd)
                            .addComponent(bLimCadProd))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 428, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(26, 26, 26))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cVlVenCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cVlVenCadProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cVlVenCadProdActionPerformed

    private void bCadCadProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCadCadProdMouseClicked
        try {
            this.cadastrarProduto();
        } catch (SQLException ex) {
            Logger.getLogger(JCadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bCadCadProdMouseClicked

    private void bLimCadProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLimCadProdMouseClicked
        this.limparCampos();
    }//GEN-LAST:event_bLimCadProdMouseClicked

    private void bLimCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimCadProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bLimCadProdActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            this.j.voltar();
        } catch (SQLException ex) {
            Logger.getLogger(JCadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void radioPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioPesoActionPerformed

    private void radioUnidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioUnidadeMouseClicked
        this.radioPeso.setSelected(false);
        this.setUnidade(true);
    }//GEN-LAST:event_radioUnidadeMouseClicked

    private void radioPesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioPesoMouseClicked
        this.radioUnidade.setSelected(false);
        this.setUnidade(false);
    }//GEN-LAST:event_radioPesoMouseClicked

    private void cCodBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cCodBarKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                this.produtoExiste();
            } catch (SQLException ex) {
                Logger.getLogger(JCadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cCodBarKeyReleased

    private void cNomCadProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cNomCadProdKeyReleased
    }//GEN-LAST:event_cNomCadProdKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCadCadProd;
    private javax.swing.JButton bLimCadProd;
    private javax.swing.JTextField cCodBar;
    private javax.swing.JTextPane cDesCadProd;
    private javax.swing.JTextField cMarCadProd;
    private javax.swing.JTextField cNomCadProd;
    private javax.swing.JFormattedTextField cVlVenCadProd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lDecCadProd1;
    private javax.swing.JLabel lMarCadProd;
    private javax.swing.JLabel lNomCadProd;
    private javax.swing.JLabel lVlVenCadProd;
    private javax.swing.JRadioButton radioPeso;
    private javax.swing.JRadioButton radioUnidade;
    // End of variables declaration//GEN-END:variables
    private Janela j;
    private boolean unidade;
    private Mensagem mensagem = new Mensagem();
        
    private void cadastrarProduto() throws SQLException{
        TrataNumeros trataNumeros = new TrataNumeros();
        
        if(this.cNomCadProd.getText().equals("") || this.cMarCadProd.getText().equals("") || 
           this.cVlVenCadProd.getText().equals("R$   .  ")){
            this.mensagem.msg();
        }else{                
            String sqlProduto = "INSERT INTO produtos (nom_prod, mar_prod, vl_prod, desc_prod, unidade, cod_bar_prod) VALUES (?, ?, ?, ?, ?, ?)";
            Connection conexao = new Conexao().getConexao();
  
            try {
                PreparedStatement stmtProduto = conexao.prepareStatement(sqlProduto);
                this.preparaStatement(stmtProduto, trataNumeros);
                stmtProduto.execute();
                conexao.commit();
                this.mensagem.msg("Produto cadastrado com sucesso!!");
                this.limparCampos();
            } catch (SQLException ex) {
                conexao.rollback();
                this.mensagem.msg("O produto não foi cadastrado!!");
            } finally {
                conexao.close();
            }
        }
    }
    
    private void preparaStatement(PreparedStatement stmtProduto, TrataNumeros trataNumeros) throws SQLException{
        stmtProduto.setString(1, this.cNomCadProd.getText().toUpperCase());
        stmtProduto.setString(2, this.cMarCadProd.getText().toUpperCase());
        stmtProduto.setFloat(3, trataNumeros.trataDinheiro(this.cVlVenCadProd.getText()));
        stmtProduto.setString(4, this.cDesCadProd.getText().toUpperCase());
        stmtProduto.setBoolean(5, this.unidade);
        
        if(this.cCodBar.getText().equals("".trim()))
            stmtProduto.setString(6, "" + new GeraCriptografa().gerarNumero(new Conexao().getConexao(), "produtos", "cod_bar_prod"));
        else
            stmtProduto.setString(6, this.cCodBar.getText());
    }
    
    private void produtoExiste() throws SQLException{
        String sql = "SELECT * FROM produtos WHERE cod_bar_prod = '" + this.cCodBar.getText() + "' LIMIT 1;";
        Connection conexao =  new Conexao().getConexao();
        
        try {
            ResultSet rs = conexao.prepareStatement(sql).executeQuery();

            if(rs == null){
               conexao.close();
               return;
            }else{
                if(rs.next()){
                    this.mensagem.msg("Produto ja foi cadastrado!!");
                    this.limparCampos();
                    conexao.close();
                    return;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(JCadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            conexao.close();
        }
    }
    
    public void limparCampos(){
        this.cNomCadProd.setText("");
        this.cMarCadProd.setText("");
        this.cVlVenCadProd.setText("");
        this.cDesCadProd.setText("");
        this.cCodBar.setText("");
        this.cDesCadProd.setText("");
    }

    /**
     * @param j the j to set
     */
    public void setJ(Janela j) {
        this.j = j;
    }

    /**
     * @return the j
     */
    public Janela getJ() {
        return j;
    }

    /**
     * @return the radioPeso
     */
    public javax.swing.JRadioButton getRadioPeso() {
        return radioPeso;
    }

    /**
     * @return the radioUnidade
     */
    public javax.swing.JRadioButton getRadioUnidade() {
        return radioUnidade;
    }

    /**
     * @return the unidade
     */
    public boolean isUnidade() {
        return unidade;
    }

    /**
     * @param unidade the unidade to set
     */
    public void setUnidade(boolean unidade) {
        this.unidade = unidade;
    }   
}
