
package br.com.walison.lucros.visao.cadastros;

import br.com.walison.lucros.classes.Conexao;
import br.com.walison.lucros.classes.GeraCriptografa;
import br.com.walison.lucros.classes.Janela;
import br.com.walison.lucros.classes.Mensagem;
import br.com.walison.lucros.classes.TrataNumeros;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Walison Cecílio
 */
public class JCadastroCliente extends javax.swing.JPanel {

    /**
     * Creates new form JCadastroCliente
     */
    public JCadastroCliente(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        cNomCadCli = new javax.swing.JTextField();
        cSobNomCadCli = new javax.swing.JTextField();
        lSobNomCadCli = new javax.swing.JLabel();
        lNomCadCli = new javax.swing.JLabel();
        lDatCadCli = new javax.swing.JLabel();
        lRuaCadCli = new javax.swing.JLabel();
        cRuaCadCli = new javax.swing.JTextField();
        lNumCadCli = new javax.swing.JLabel();
        cNumCasa = new javax.swing.JFormattedTextField();
        cDatCadCli = new javax.swing.JFormattedTextField();
        lTelCadCli = new javax.swing.JLabel();
        cTelCadCli = new javax.swing.JFormattedTextField();
        cConjCadCli = new javax.swing.JTextField();
        lConjCadCli = new javax.swing.JLabel();
        lBaiCadCli = new javax.swing.JLabel();
        lLimCadCli = new javax.swing.JLabel();
        lDatPagCadCli = new javax.swing.JLabel();
        cCpfCadCli = new javax.swing.JFormattedTextField();
        lCpfCadCli = new javax.swing.JLabel();
        cDatPagCadCli = new javax.swing.JFormattedTextField();
        cCidCadCli = new javax.swing.JTextField();
        lCidCadCli = new javax.swing.JLabel();
        cBaiCadCli = new javax.swing.JTextField();
        bCadCadCli = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bLimCadCli = new javax.swing.JButton();
        cLimCadCli = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();

        jLabel12.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        jLabel12.setText("CADASTRO DE CLIENTE");

        cNomCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        cNomCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNomCadCliActionPerformed(evt);
            }
        });
        cNomCadCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cNomCadCliKeyPressed(evt);
            }
        });

        cSobNomCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        cSobNomCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSobNomCadCliActionPerformed(evt);
            }
        });
        cSobNomCadCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cSobNomCadCliKeyPressed(evt);
            }
        });

        lSobNomCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lSobNomCadCli.setText("SOBRENOME:  *");

        lNomCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lNomCadCli.setText("NOME:  *");

        lDatCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lDatCadCli.setText("DATA NASCIMENTO:");

        lRuaCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lRuaCadCli.setText("RUA:");

        cRuaCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        cRuaCadCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cRuaCadCliKeyPressed(evt);
            }
        });

        lNumCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lNumCadCli.setText("NÚMERO:");

        try {
            cNumCasa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cNumCasa.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        cNumCasa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cNumCasaKeyPressed(evt);
            }
        });

        try {
            cDatCadCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cDatCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        cDatCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cDatCadCliActionPerformed(evt);
            }
        });
        cDatCadCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cDatCadCliKeyPressed(evt);
            }
        });

        lTelCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lTelCadCli.setText("CONTATO:");

        try {
            cTelCadCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cTelCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        cTelCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTelCadCliActionPerformed(evt);
            }
        });
        cTelCadCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cTelCadCliKeyPressed(evt);
            }
        });

        cConjCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        cConjCadCli.setText("SANTO ANTÔNIO");
        cConjCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cConjCadCliActionPerformed(evt);
            }
        });
        cConjCadCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cConjCadCliKeyPressed(evt);
            }
        });

        lConjCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lConjCadCli.setText("CONJUNTO:");

        lBaiCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lBaiCadCli.setText("BAIRRO:");

        lLimCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lLimCadCli.setText("LIMITE:  *");

        lDatPagCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lDatPagCadCli.setText("DIA DE PAGAMENTO:  *");

        try {
            cCpfCadCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cCpfCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        cCpfCadCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cCpfCadCliKeyPressed(evt);
            }
        });

        lCpfCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lCpfCadCli.setText("CPF:  *");

        try {
            cDatPagCadCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cDatPagCadCli.setToolTipText("Dia");
        cDatPagCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        cDatPagCadCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cDatPagCadCliKeyPressed(evt);
            }
        });

        cCidCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        cCidCadCli.setText("ESTÂNCIA");
        cCidCadCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cCidCadCliKeyPressed(evt);
            }
        });

        lCidCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lCidCadCli.setText("CIDADE:");

        cBaiCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        cBaiCadCli.setText("CIDADE NOVA");
        cBaiCadCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cBaiCadCliKeyPressed(evt);
            }
        });

        bCadCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        bCadCadCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/salvar.png"))); // NOI18N
        bCadCadCli.setToolTipText("Cadastrar Cliente");
        bCadCadCli.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bCadCadCli.setBorderPainted(false);
        bCadCadCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCadCadCliMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 12)); // NOI18N
        jLabel2.setText("CAMPOS CONTENDO * SÃO OBRIGATÓTIOS");

        bLimCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        bLimCadCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/lixeira.png"))); // NOI18N
        bLimCadCli.setToolTipText("Limpar Campos");
        bLimCadCli.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bLimCadCli.setBorderPainted(false);
        bLimCadCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLimCadCliMouseClicked(evt);
            }
        });
        bLimCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimCadCliActionPerformed(evt);
            }
        });

        try {
            cLimCadCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("R$ ###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cLimCadCli.setText("R$ 100");
        cLimCadCli.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        cLimCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cLimCadCliActionPerformed(evt);
            }
        });
        cLimCadCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cLimCadCliKeyPressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/voltar.png"))); // NOI18N
        jButton1.setToolTipText("Voltar");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lRuaCadCli)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cRuaCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lNumCadCli)
                                                .addGap(7, 7, 7)
                                                .addComponent(cNumCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lConjCadCli))
                                            .addComponent(lDatCadCli))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(297, 297, 297)
                                                .addComponent(cLimCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cConjCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lBaiCadCli)
                                                .addGap(18, 18, 18)
                                                .addComponent(cBaiCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(bCadCadCli)
                                        .addGap(68, 68, 68)
                                        .addComponent(bLimCadCli)
                                        .addGap(69, 69, 69)
                                        .addComponent(jButton1)
                                        .addGap(198, 198, 198)))
                                .addGap(18, 18, 18)
                                .addComponent(lCidCadCli)
                                .addGap(18, 18, 18)
                                .addComponent(cCidCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lNomCadCli)
                                .addGap(1, 1, 1)
                                .addComponent(cNomCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lSobNomCadCli)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cSobNomCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lCpfCadCli)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cCpfCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cDatCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lTelCadCli)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cTelCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(lLimCadCli)
                                .addGap(126, 126, 126)
                                .addComponent(lDatPagCadCli)
                                .addGap(3, 3, 3)
                                .addComponent(cDatPagCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(433, 433, 433)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel12)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNomCadCli)
                    .addComponent(cNomCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSobNomCadCli)
                    .addComponent(cSobNomCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCpfCadCli)
                    .addComponent(cCpfCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDatCadCli)
                    .addComponent(cDatCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTelCadCli)
                    .addComponent(cTelCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lLimCadCli)
                    .addComponent(cLimCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDatPagCadCli)
                    .addComponent(cDatPagCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lRuaCadCli)
                    .addComponent(cRuaCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNumCadCli)
                    .addComponent(lConjCadCli)
                    .addComponent(cConjCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lBaiCadCli)
                    .addComponent(cBaiCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCidCadCli)
                    .addComponent(cCidCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cNumCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bCadCadCli)
                        .addComponent(bLimCadCli))
                    .addComponent(jButton1))
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cNomCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNomCadCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cNomCadCliActionPerformed

    private void cNomCadCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cNomCadCliKeyPressed
        this.eventoCadastrarEnter(evt);
    }//GEN-LAST:event_cNomCadCliKeyPressed

    private void cSobNomCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSobNomCadCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cSobNomCadCliActionPerformed

    private void cSobNomCadCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cSobNomCadCliKeyPressed
        this.eventoCadastrarEnter(evt);
    }//GEN-LAST:event_cSobNomCadCliKeyPressed

    private void cRuaCadCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cRuaCadCliKeyPressed
        this.eventoCadastrarEnter(evt);
    }//GEN-LAST:event_cRuaCadCliKeyPressed

    private void cNumCasaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cNumCasaKeyPressed
        this.eventoCadastrarEnter(evt);
    }//GEN-LAST:event_cNumCasaKeyPressed

    private void cDatCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cDatCadCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cDatCadCliActionPerformed

    private void cDatCadCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cDatCadCliKeyPressed
        this.eventoCadastrarEnter(evt);
    }//GEN-LAST:event_cDatCadCliKeyPressed

    private void cTelCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTelCadCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cTelCadCliActionPerformed

    private void cTelCadCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cTelCadCliKeyPressed
        this.eventoCadastrarEnter(evt);
    }//GEN-LAST:event_cTelCadCliKeyPressed

    private void cConjCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cConjCadCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cConjCadCliActionPerformed

    private void cConjCadCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cConjCadCliKeyPressed
        this.eventoCadastrarEnter(evt);
    }//GEN-LAST:event_cConjCadCliKeyPressed

    private void cCpfCadCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cCpfCadCliKeyPressed
        this.eventoCadastrarEnter(evt);
    }//GEN-LAST:event_cCpfCadCliKeyPressed

    private void cDatPagCadCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cDatPagCadCliKeyPressed
        this.eventoCadastrarEnter(evt);
    }//GEN-LAST:event_cDatPagCadCliKeyPressed

    private void cCidCadCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cCidCadCliKeyPressed
        this.eventoCadastrarEnter(evt);
    }//GEN-LAST:event_cCidCadCliKeyPressed

    private void cBaiCadCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cBaiCadCliKeyPressed
        this.eventoCadastrarEnter(evt);
    }//GEN-LAST:event_cBaiCadCliKeyPressed

    private void bCadCadCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCadCadCliMouseClicked
        try {
            this.cadastrarCliente();
        } catch (SQLException ex) {
            Logger.getLogger(JCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bCadCadCliMouseClicked

    private void bLimCadCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLimCadCliMouseClicked
        this.limparCampos();
    }//GEN-LAST:event_bLimCadCliMouseClicked

    private void bLimCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimCadCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bLimCadCliActionPerformed

    private void cLimCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cLimCadCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cLimCadCliActionPerformed

    private void cLimCadCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cLimCadCliKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                this.cadastrarCliente();
            } catch (SQLException ex) {
                Logger.getLogger(JCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cLimCadCliKeyPressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            this.j.voltar();
        } catch (SQLException ex) {
            Logger.getLogger(JCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCadCadCli;
    private javax.swing.JButton bLimCadCli;
    private javax.swing.JTextField cBaiCadCli;
    private javax.swing.JTextField cCidCadCli;
    private javax.swing.JTextField cConjCadCli;
    private javax.swing.JFormattedTextField cCpfCadCli;
    private javax.swing.JFormattedTextField cDatCadCli;
    private javax.swing.JFormattedTextField cDatPagCadCli;
    private javax.swing.JFormattedTextField cLimCadCli;
    private javax.swing.JTextField cNomCadCli;
    private javax.swing.JFormattedTextField cNumCasa;
    private javax.swing.JTextField cRuaCadCli;
    private javax.swing.JTextField cSobNomCadCli;
    private javax.swing.JFormattedTextField cTelCadCli;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lBaiCadCli;
    private javax.swing.JLabel lCidCadCli;
    private javax.swing.JLabel lConjCadCli;
    private javax.swing.JLabel lCpfCadCli;
    private javax.swing.JLabel lDatCadCli;
    private javax.swing.JLabel lDatPagCadCli;
    private javax.swing.JLabel lLimCadCli;
    private javax.swing.JLabel lNomCadCli;
    private javax.swing.JLabel lNumCadCli;
    private javax.swing.JLabel lRuaCadCli;
    private javax.swing.JLabel lSobNomCadCli;
    private javax.swing.JLabel lTelCadCli;
    // End of variables declaration//GEN-END:variables
    private Mensagem mensagem = new Mensagem();
    private Janela j;
    
    private void cadastrarCliente() throws SQLException{
        TrataNumeros trataNumeros = new TrataNumeros();
        
        if(cSobNomCadCli.getText().equals("") || this.cNomCadCli.getText().equals("") || 
           this.cCpfCadCli.getText().equals("   .   .   -  ") || this.cLimCadCli.getText().equals("R$    ") ||
           this.cDatPagCadCli.getText().equals("  /  /    ")){
           this.mensagem.msg();
        }else{
            Connection conexao = new Conexao().getConexao();

            int cod_con = new GeraCriptografa().gerarNumero(conexao, "contas", "cod_con");
            int numCasa;
            
            if(!this.cNumCasa.getText().equals("   ")){
                numCasa = Integer.parseInt(this.cNumCasa.getText());
            }else{
                numCasa = 0;
            }
            
            if(this.cDatCadCli.getText().equals("  /  /    "))
                this.cDatCadCli.setText("11/11/1111");      
            
            String sqlCliente = "INSERT INTO clientes (nom_cli, sob_nom_cli, cpf_cli, dt_nasc_cli, cod_con, rua_cli,"
            + "num_cas_cli, conj_cli, bai_cli, cid_cli, uf_cli, tel_cli) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
 
            String sqlConta = "INSERT INTO contas (cod_con, lim_con, dt_pag) VALUES (?, ?, ?)";
                        
            try {
                PreparedStatement stmtConta = conexao.prepareStatement(sqlConta);
                PreparedStatement stmtCliente = conexao.prepareStatement(sqlCliente);
                
                this.preparaStatementConta(stmtConta, cod_con, trataNumeros);
                this.preparaStatementCliente(stmtCliente, cod_con, numCasa, trataNumeros);
                
                stmtConta.execute();
                stmtCliente.execute();                
                conexao.commit();
                this.mensagem.msg("Cliente cadastrato com sucesso!!");
                this.limparCampos();
            } catch (SQLException ex) {
                this.mensagem.msg("Não foi possivel cadastrar cliente!!");
                System.err.println(ex);
                conexao.rollback();
            } finally {
                conexao.close();
            }
        }
    }
    
    private void preparaStatementConta(PreparedStatement stmtConta, int cod_con, TrataNumeros trataNumeros) throws SQLException{
        stmtConta.setInt(1, cod_con);
        stmtConta.setFloat(2, trataNumeros.trataDinheiro(this.cLimCadCli.getText()));
        stmtConta.setString(3, this.cDatPagCadCli.getText());
    }
    
    private void preparaStatementCliente(PreparedStatement stmtCliente, int cod_con, int numCasa,TrataNumeros trataNumeros) throws SQLException{
        stmtCliente.setString(1, this.cNomCadCli.getText().toUpperCase());
        stmtCliente.setString(2, this.cSobNomCadCli.getText().toUpperCase());
        stmtCliente.setString(3, trataNumeros.trataNumeros(this.cCpfCadCli.getText()));
        stmtCliente.setString(4, trataNumeros.trataDatas(this.cDatCadCli.getText()));
        stmtCliente.setInt(5, cod_con);
        stmtCliente.setString(6, this.cRuaCadCli.getText().toUpperCase());
        stmtCliente.setInt(7, numCasa);
        stmtCliente.setString(8, this.cConjCadCli.getText().toUpperCase());
        stmtCliente.setString(9, this.cBaiCadCli.getText().toUpperCase());
        stmtCliente.setString(10, this.cCidCadCli.getText().toUpperCase());
        stmtCliente.setString(11, "SE");
        stmtCliente.setString(12, this.cTelCadCli.getText());
    }
    
    private void limparCampos(){
        this.cTelCadCli.setText("");
        this.cSobNomCadCli.setText("");
        this.cRuaCadCli.setText("");
        this.cNumCasa.setText("");
        this.cNomCadCli.setText("");
        this.cLimCadCli.setText("100");
        this.cDatCadCli.setText("");
        this.cCpfCadCli.setText("");
        this.cConjCadCli.setText("SANTO ANTÔNIO");
        this.cCidCadCli.setText("ESTÂNCIA");
        this.cBaiCadCli.setText("CIDADE NOVA");
    }
    
    private void eventoCadastrarEnter(java.awt.event.KeyEvent evt){
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                this.cadastrarCliente();
            } catch (SQLException ex) {
                Logger.getLogger(JCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    /**
     * @param j the j to set
     */
    public void setJ(Janela j) {
        this.j = j;
    }

    /**
     * @return the j
     */
    public Janela getJ() {
        return j;
    }
}
