package br.com.walison.lucros.visao.listagem;

import br.com.walison.lucros.classes.Calendario;
import br.com.walison.lucros.classes.modelos.Subtotal;
import br.com.walison.lucros.classes.Conexao;
import br.com.walison.lucros.classes.FormatoNumerico;
import br.com.walison.lucros.classes.Janela;
import br.com.walison.lucros.classes.Mensagem;
import br.com.walison.lucros.classes.Sistema;
import br.com.walison.lucros.classes.TrataNumeros;
import br.com.walison.lucros.classes.modelos.Venda;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Walison Cecílio
 */
public class JListarVendas extends javax.swing.JPanel {

    /**
     * Creates new form JListarVendas
     */
    public JListarVendas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bDetalhes = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        data2 = new com.toedter.calendar.JDateChooser();
        data1 = new com.toedter.calendar.JDateChooser();

        jTable1.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD", "V COMPRA", "V RECEBIDO", "V TROCO", "DATA ", "HORA"
            }
        ));
        jTable1.setRowHeight(25);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        bDetalhes.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        bDetalhes.setText("DETALHES");
        bDetalhes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bDetalhesMouseClicked(evt);
            }
        });
        bDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDetalhesActionPerformed(evt);
            }
        });
        bDetalhes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bDetalhesKeyPressed(evt);
            }
        });

        jButton2.setText("BUSCAR ENTRE DATAS");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jButton3.setText("VOLTAR");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        jLabel1.setText("ATÉ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(data1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addComponent(data2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jScrollPane1)))
                .addGap(119, 119, 119))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bDetalhes)
                .addGap(36, 36, 36)
                .addComponent(jButton3)
                .addGap(313, 313, 313))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {data1, data2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(data2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(data1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(bDetalhes))
                .addGap(44, 44, 44))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDetalhesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bDetalhesActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    }//GEN-LAST:event_jTable1MouseClicked

    private void bDetalhesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bDetalhesKeyPressed
      
    }//GEN-LAST:event_bDetalhesKeyPressed

    private void bDetalhesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDetalhesMouseClicked
        int index = this.jTable1.getSelectedRow();
        
        if(index > -1){
            Venda venda = (Venda) this.jTable1.getValueAt(index, 0);

            Janela j = new Janela(1200, 600);
            JDetalhesCompra a = new JDetalhesCompra();
            try {
                venda.CarregarVenda();
                a.setVenda(venda);
                FormatoNumerico f = new FormatoNumerico();
                TrataNumeros t = new TrataNumeros();
                
                a.getNome1().setText("VENDA REALIZADA EM " + t.tranformaDataLegivel(a.getVenda().getDt_com_prod()) + " às " + a.getVenda().getHr_com_prod());
                a.getNome2().setText("VALOR DA VENDA: " + f.din(a.getVenda().getVl_ven()));

                this.setJ2(j);

                DefaultTableModel model = (DefaultTableModel) a.getjTable1().getModel();

                int cont = 1;
                for(Subtotal c : venda.getCompras()){
                    Object[] linha = {cont++, c.getProduto(), c.getQtd_prod(), f.din(c.getVl_prod()), f.din(c.getVl_com())}; 
                    model.addRow(linha);
                }

                j2.setVisible(true);
                j2.setResizable(false);
                j2.add(a);
                a.setJ2(j2);
                a.setJ(this.j);

                this.j.setEnabled(false);
            } catch (SQLException ex) {
                Logger.getLogger(JListarVendas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            new Mensagem().msg("Selecione uma venda para ver os detalhes!!");
        }
    }//GEN-LAST:event_bDetalhesMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        try {
            this.BuscarEntreDatas();
        } catch (SQLException ex) {
            Logger.getLogger(JListarVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
       
    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        try {
            this.j.voltar();
        } catch (SQLException ex) {
            Logger.getLogger(JListarVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDetalhes;
    private com.toedter.calendar.JDateChooser data1;
    private com.toedter.calendar.JDateChooser data2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    private LinkedList<Venda> vedas;
    private Janela j;
    private Janela j2;
    private Sistema sis = new Sistema();
    private Mensagem mensagem = new Mensagem();
    private NumberFormat dim = NumberFormat.getCurrencyInstance();

    private void BuscarEntreDatas() throws SQLException{
        LinkedList<Venda> vendas = new LinkedList<>();
        ResultSet r;
        TrataNumeros t = new TrataNumeros();
        Calendario c = new Calendario();
        
        Connection conexao = new Conexao().getConexao();
        if(c.retornaData(this.data1.getDate()).equals("") || c.retornaData(this.getData2().getDate()).equals(t.trataDatas(c.retornaData())))
            r = conexao.createStatement().executeQuery("SELECT * FROM vendas ORDER BY dt_com_prod desc");
        else
            r = conexao.createStatement().executeQuery("SELECT * FROM vendas WHERE dt_com_prod between ('" + t.trataDatas(c.retornaData(this.data1.getDate())) + "') and ('" + t.trataDatas(c.retornaData(this.getData2().getDate())) + "') ORDER BY dt_com_prod desc");

        while(r.next()){
            vendas.add(new Venda(r.getShort(1), r.getFloat(2), r.getFloat(7), r.getFloat(8), r.getString(4), r.getString(5)));
        }
       
        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
        model.setNumRows(0);
        
        for(Venda v : vendas){
            Object[] linha = {v, v.getVl_ven(), v.getVl_recebido(), v.getVl_troco(), t.tranformaDataLegivel(v.getDt_com_prod()), v.getHr_com_prod()};
            model.addRow(linha);
        }
        
    }
    
    /**
     * @return the jTable1
     */
    public javax.swing.JTable getjTable1() {
        return jTable1;
    }

    /**
     * @return the vedas
     */
    public LinkedList<Venda> getVedas() {
        return vedas;
    }

    /**
     * @param vedas the vedas to set
     */
    public void setVedas(LinkedList<Venda> vedas) {
        this.vedas = vedas;
    }

    /**
     * @return the j
     */
    public Janela getJ() {
        return j;
    }

    /**
     * @param j the j to set
     */
    public void setJ(Janela j) {
        this.j = j;
    }

    /**
     * @return the j2
     */
    public Janela getJ2() {
        return j2;
    }

    /**
     * @param j2 the j2 to set
     */
    public void setJ2(Janela j2) {
        this.j2 = j2;
    }

    /**
     * @return the sis
     */
    public Sistema getSis() {
        return sis;
    }

    /**
     * @return the mensagem
     */
    public Mensagem getMensagem() {
        return mensagem;
    }

    /**
     * @return the dim
     */
    public NumberFormat getDim() {
        return dim;
    }

    /**
     * @return the data2
     */
    public com.toedter.calendar.JDateChooser getData2() {
        return data2;
    }

    /**
     * @param data2 the data2 to set
     */
    public void setData2(com.toedter.calendar.JDateChooser data2) {
        this.data2 = data2;
    }
}
